### ISSUE TITLE
Autocompletion fails with nested classes

### ISSUE THREAD

**Issue by amol-mandhane** [mopemope/meghanada-emacs#13]
I have a library which has a lot of nested classes (protocol buffer generated source). The autocompletion is suggesting the nested class completion as ParentClass$NestedClass with ParentClass import instead of importing NestedClass directly.

Also, the autocompletion is not suggesting anything for any methods/parameters of the nested class.

**Comment by mopemope** [comment]
@amol-mandhane  Please would you tell me more details ?

**Comment by amol-mandhane** [comment]
If you have a class structure as follows

```java
public class TopClass {
  public class NestedClass {
    public void nestedClassMethod() {}
  }
  
  public void topClassMethod() {}
}
```

If you try to autocomplete `TopClass`, it works correctly with correct import. If you try to autocomplete `topClassMethod` on an instance of `TopClass`, it works correctly.

However, if you try to autocomplete `NestedClass`, it will autocomplete as `TopClass$NestedClass` and it will import `TopClass`. The correct behavior is importing `NestedClass` directly and autocompleting as `NestedClass`. Also, autocompletion gives no suggestion for methods and fields of `NestedClass` instance. The correct behavior is to suggest `nestedClassMethod`.

**Comment by mopemope** [comment]
@amol-mandhane I have fixed it. Please check latest version (v0.2.2). and call M-x meghanada-update-server.

**Comment by amol-mandhane** [comment]
@mopemope M-x meghanada-update-server is downloading v0.2.0

Also, autocompletion is not working for annotations as well. Should I file a separate issue for this?

**Comment by mopemope** [comment]
@amol-mandhane Thank you for your report. Meghanada dose not support annotations completion yet.

**Comment by mopemope** [comment]
@amol-mandhane Meghanada to begin support annotation completion since 0.2.4 .  Please try 0.2.4.
![annotation](https://cloud.githubusercontent.com/assets/22645/19483073/03b498e4-958e-11e6-8a00-8817fd60fa99.png)

**Comment by amol-mandhane** [comment]
@mopemope : Annotation completion is working. But NestedClass issue still not fixed.

**Comment by amol-mandhane** [comment]
Any update on this?

**Comment by mopemope** [comment]
@amol-mandhane  I have fixed it. Please check latest version.
